package opensgs.enums;

public enum Operacion {
    Crear,
    Modificar,
    ModificarMisDatos,
    ModificarMiContraseña,
    ModificarContraseña,
    ModificarMiSolicitud,
    RecuperarContraseña,
    Borrar,
    Restaurar,
    IniciarSesion,
    CerrarSesion,
    Registrar,
    Invitar,
    Guardar,
    Acordar,
    Entregar,
    NoEntregar,
    EntregarMiSolicitud,
    Financiar,
    NoFinanciar,
    Cursar,
    NoCursar,
    Aprobar,
    NoAprobar,
    Agregar,
    Quitar,
    Ver,
    VerMisDatos,
    VerMisSolicitudes,
    VerMisConstancias,
    Desactivar,
    Activar,
    Todas
}
